### ISSUE TITLE
Add git commands to Git hooks

### ISSUE THREAD

**Issue by alopesmendes** [alopesmendes/Anime-Seas#2]
# Add git commands

## Features
- pre-commit: Should format files and fail if it cannot reformat files
- commit-msg: After the message is created, it should add the current branch and check that commit-msg is not too long
- pre-push: always rebase with the main before pushing

## Tasks
- [x] Search for a library in kotlin (ktlin or deteckt)
- [x] Create a bash script for pre-commit
- [x] Create a task preCommit to copy in git hooks
- [x] Create a bash script for commit-msg
- [x] Create a task commitMsg to copy in git hooks
