### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by alopesmendes** [alopesmendes/Anime-Seas#3]
## Description
Add CI/CD into the project. For now, we will focus on Android, Desktop, and web. 

## Features
The following steps for the CI/CD
build -> test -> analyse -> (deploy)

## Tasks
- [ ] Create tags to run different pipelines for only Android, Desktop, etc
- [ ] Add two tests, a unit test, and a UI test
- [ ] Look how to build with fastlane
- [ ] Add the steps to build the project
- [ ] Add the steps to test the project
- [ ] Add the steps to analyze the code
- [ ] Add conditions to have a pipeline created only for pull requests
